spring:
  application:
    name: Rom-Storage
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5434/rom_storege_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  security:
    admin-key: ${ADMIN_API_KEY}
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
google:
  drive:
    folder-id: ${FOLDER_ID}
    credentials-path: ${GOOGLE_CREDENTIALS_PATH}